name: Go

on: [push]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        go: ['1.22', '1.23', 'stable']

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - id: go
      name: Setup
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v -coverprofile=profile.cov .

    - name: Coverage
      run: bash <(curl -s https://codecov.io/bash) -f profile.cov
